server:
  port: 8080
  connection-timeout: 60000 # 下载文件的超时时间

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test

#fdfs:
#  soTimeout: 1501        # 读取时间
#  connectTimeout: 691    # 连接超时时间
#  #charset: UTF-8       # 编码默认UTF-8，charset属性不能自定义
#  thumbImage:            # 缩略图
#    width: 150              # 宽
#    height: 150             # 高
#  trackerList:           # tracker列表
#    - 172.18.10.144:22122
#    - 172.18.10.144:22122
